;//////////////////////////////////////////////////////////////////////////////
;FILE: CommandMap.ini (SYSTEM) ////////////////////////////////////////////////////
;//////////////////////////////////////////////////////////////////////////////



; Send selected free builders to the nearest abandoned construction sites.
CommandMap RESUME_NEAREST_CONSTRUCTION
  Key = KEY_B
  Transition = DOWN
  Modifiers = SHIFT_CTRL
  UseableIn = GAME
End
